### ISSUE TITLE
Displaying a single html file as thumb

### ISSUE THREAD

**Issue by Athanaseus** [ratt-ru/radiopadre#76]
When displaying an `html` file as a thumb, it appears slightly blurred and does not fit the output cell.
I also tried the full-width mode of the notebook cells but thumb appears to be trimmed off.

I did the following:

```
from radiopadre import ls
rfinder_file = "rfi_q*/time_report.html"
rfinder_plot = ls(rfinder_file, section="Target RFInder")
rfinder_plot[0].thumb
```

results:

![Screenshot from 2020-03-24 10-16-36](https://user-images.githubusercontent.com/16665629/77405366-bfa82080-6dbb-11ea-965c-c046208d9cc2.png)

**Comment by o-smirnov** [comment]
Can you give me a path to the notebook?

(For this and future reports, if it's on a Rhodes machine, always give me a path, that's the quickest way for me to check...)

**Comment by Athanaseus** [comment]
Noted, here we go `/home/ramaila/working/PicA/output5` on stills

**Comment by o-smirnov** [comment]
The default width of the output raster was hardcoded to 800px, which was way too low. I've changed it to 1920px. This may be too high. I don't know how to pick this automatically, as it really depends on the HTML being rendered. So I added ``width`` and ``height`` options. You can either pass them to thumb(), or use settings i.e.:

```python
with settings.html(width=1024, height=768):
   # render stuff
```

or even simpler (but then persistent through the document):

```
settings.html.width = 1024
```

I would welcome better ideas and improvements to the HTML rendering. The current system is dead simple: [htmlfile objects](https://github.com/ratt-ru/radiopadre/blob/b1.0-pre9/radiopadre/htmlfile.py) invoke [phantomjs](https://phantomjs.org/examples.html) with [this script](https://github.com/ratt-ru/radiopadre/blob/master/radiopadre/html/html-thumbnail.js]), and that's all there is to it.

**Comment by Athanaseus** [comment]
After setting the width to what was said to be the default (`settings.html.width = 800`), the thumbs don't appear as expected.

This is how they appear:
![Screenshot from 2020-03-30 16-09-19](https://user-images.githubusercontent.com/16665629/77922132-ef19ca00-72a0-11ea-97ec-7876b707e313.png)

For instance check `pica-PicA-1gc1_primary_cal.K1.html`, which if you `Open image in new tab` gives:

![Screenshot from 2020-03-30 16-13-28](https://user-images.githubusercontent.com/16665629/77922669-9e56a100-72a1-11ea-9b94-d3920fd31f58.png)

NB: `pica-PicA-1gc1_primary_cal.K0.html` and `pica-PicA-1gc1_primary_cal.K1.html` are the similar plots but apear different.

**Comment by o-smirnov** [comment]
> NB: pica-PicA-1gc1_primary_cal.K0.html and pica-PicA-1gc1_primary_cal.K1.html are the similar plots but apear different.

Yeah that's especially weird. Link to output dir and notebook please?

**Comment by Athanaseus** [comment]
On stills `/home/ramaila/working/PicA/output7/std-progress-report-Copy1.ipynb`

**Comment by o-smirnov** [comment]
Currently can't reproduce. I ran your notebook, and all the thumbs look fine to me.

Note that I changed the top to ``settings.html.width = settings.html.height = 800``. The default height of 1920 is a bit too much, and made for very tall thumbnails.

**Comment by Athanaseus** [comment]
Ah yes, I noticed when I re-ran it looked fine, thanks.

I also tried below size definition, but it seems like it does not work:
```
rfinder_plot.html.thumbs(width=400, height=400)
```
This is specifically for the `rfinder` report which we agreed can just be rendered as png. I get:
![400 time_report](https://user-images.githubusercontent.com/16665629/78569683-40d3ce80-7824-11ea-9b82-428dd6798d15.png)

It would be nice if it can fit the output cell since it's the only thumb.

Secondly, I rendered the `aimfast` plots but they are just blank. When clicked they display fine.
See below:
![Screenshot from 2020-04-06 17-03-55](https://user-images.githubusercontent.com/16665629/78573178-b477da80-7828-11ea-9e38-fb7ac20ea3c2.png)



Thirdly, Is it possible to render `svg`? For instance, `sunblocker` produce these file formats. I get the following:

![Screenshot from 2020-04-06 16-46-53](https://user-images.githubusercontent.com/16665629/78571475-842f3c80-7826-11ea-967b-b966553335c6.png)

Fourthly, I successfully rendered `pdf` as thumb, but when I click open nothing shows (might be my poor bandwidth maybe). See the following section:

![Screenshot from 2020-04-06 16-52-02](https://user-images.githubusercontent.com/16665629/78571916-159eae80-7827-11ea-9e0f-b1a94aeb9bfe.png)

Notebook reference: `/home/ramaila/working/WLM/output/std-progress-report-Copy1.ipynb` on stills.ru.ac.za

**Comment by Athanaseus** [comment]
PS: I also tried the following when rendering an (`rfinder`) html:
```
with settings.html(width=500, height=500):
   # render stuff
```

This was didn't change the size of the rendered html.

**Comment by Athanaseus** [comment]
@o-smirnov I posted the issue here.

**Comment by o-smirnov** [comment]
OK @Athanaseus you're just steering this boat in the wrong direction. But that maybe my fault for sticking the rudder on backwards. :)

You need to make your width/height **bigger** not smaller. These settings determine the size of the canvas ("virtual browser window") to which PhantomJS renders the HTML. You've been telling it to render these pages into a very small browser. 

It's actually a two-step process: PhantomJS renders the page to a PNG of the specified size, and radiopadre then compresses that into a thumbnail. The apparent size of the thumbnail is anyway determined by the rows/columns layout, even if the original canvas is bigger.

**Comment by Athanaseus** [comment]
If I increase the size I get:

![Screenshot from 2020-04-08 11-59-19](https://user-images.githubusercontent.com/16665629/78771517-91683a80-7990-11ea-8bb5-50c2de845a53.png)

**Comment by o-smirnov** [comment]
More! More! Would you look at this report with an 800-pixel-wide browser?

Try width=1920,height=1024.

**Comment by o-smirnov** [comment]
Hehe, sorry about that @Athanaseus. There was a ridiculous number of bugs all consipring to stop this from working!

* the HTML wasn't being re-rendered when you changed width/height (normally the image cache is smart about this, but it wasn't getting the right inputs...). Fixed.

* tabulate() didn't work right when the number of items was less than the number of columns. Fixed.

* ``settings.display`` weren't being updated from the browser size, which messed with the resolution of thumbnail images. Fixed and improved.

With regard to the second point, there's a subtlety. The default width of a thumbnail image is, by default, optimized for the minimal number of columns in a thumbnail catalog (which is, by default, 2). It's set to ``display.cell_width/thumb.mincol`` somewhere in the code. If you invoke ``thumbs`` (plural!) on a **filelist** containing 1 file, it renders as two columns, with the thumbnail image on the left, and blank space on the right. The point is, the thumbnail looks good because it's rendered into half a cell's width, as expected.

However, if you invoke ``thumb`` (singular!) on just the one file, you get a rendering of the one thumbnail all on its own, but now it's displayed in a full-width cell output. This looks a bit crappy, because the thumbnail is at a lower resolution than the space it's being displayed in. 

So if you want a neat display of a thumb from just one file, you need to do one of the following (after you've updated to the latest radiopadre):

* make a filelist from that one file and use ``thumbs()`` (you'll get a half-width thumbnail, and an empty column on the right)

* you can achieve the same effect by sticking the thumb into a ``Table``, and forcing an empty second column (with ncol=2, cw="equal")

* make it full size, but then force the thumbnail to a higher resolution via ``settings.thumb.width``. I.e. something like

```python
with settings.html(width=1920), settings.thumb(width=settings.display.cell_width):
    file.thumb.show()
```

I'm pushing a new docker image already.
